### ISSUE TITLE
would it be possible to add a way to specify location of ssh-agent.exe?

### ISSUE THREAD

**Issue by ericblade** [raeesbhatti/ssh-agent-helper#4]
I've never really wanted to add the entire \program files\git\usr\bin to my path, to avoid causing potential issues with other windows scripts, so could an option be added easily to specify the path to ssh-agent ?

**Comment by RaeesBhatti** [comment]
It only requires that the `ssh-add`, `ssh-agent`,  and `ssh` are in your `PATH`. While we could add parameters to specify the location of these programs. I don't think is a good thing to do, because you're still going to need `ssh` to be in your `PATH` to use it easily.
So, I would advise you to create a new directory, copy `ssh` programs to it and then add that directory to your `PATH`. That will not pollute your `PATH` with UNIX utilities but fix the problem.
